"""scan scores

Revision ID: d74cfd6c3bc1
Revises: 77100985dceb
Create Date: 2026-09-16 23:12:17.139744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd74cfd6c3bc1'
down_revision: Union[str, Sequence[str], None] = '77100985dceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_scores',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('rubric_version', sa.String(length=16), nullable=False),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('incomplete_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_loc', sa.Integer(), nullable=False),
    sa.Column('module_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scan_scores_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id', name=op.f('pk_scan_scores'))
    )
    op.add_column('findings', sa.Column('score_impact', sa.Float(), nullable=True))
    op.add_column('scans', sa.Column('source_loc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'source_loc')
    op.drop_column('findings', 'score_impact')
    op.drop_table('scan_scores')
    # ### end Alembic commands ###
