"""llm enrichment

Revision ID: 77100985dceb
Revises: 32553c8021fb
Create Date: 2026-09-16 22:38:53.487607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77100985dceb'
down_revision: Union[str, Sequence[str], None] = '32553c8021fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written: autogenerate doesn't detect new enum values or create enum types
    # for add_column.
    op.execute("ALTER TYPE scan_status ADD VALUE IF NOT EXISTS 'analysis_complete' AFTER 'running'")
    op.execute("ALTER TYPE scan_status ADD VALUE IF NOT EXISTS 'enriching' AFTER 'analysis_complete'")
    enrichment_status = postgresql.ENUM(
        'pending', 'running', 'completed', 'partial', 'failed', 'skipped', name='enrichment_status'
    )
    enrichment_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('fix_suggestion', 'fix_regeneration', 'architecture_review', name='llm_purpose'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('pending', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reserved_tokens', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_llm_calls_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index('ix_llm_calls_scan_id_purpose', 'llm_calls', ['scan_id', 'purpose'], unique=False)
    op.create_table('architecture_reviews',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ready', 'failed', name='architecture_review_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('dropped_issues', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('suggested_target_structure', sa.Text(), nullable=True),
    sa.Column('citations_total', sa.Integer(), nullable=False),
    sa.Column('citations_invalid', sa.Integer(), nullable=False),
    sa.Column('hallucination_rate', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('llm_call_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], name=op.f('fk_architecture_reviews_llm_call_id_llm_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_architecture_reviews_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id', name=op.f('pk_architecture_reviews'))
    )
    op.create_table('fix_suggestions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('generating', 'ready', 'failed', name='fix_status'), nullable=False),
    sa.Column('validation_status', sa.Enum('valid', 'failed_to_apply', 'syntax_error', 'no_patch', 'not_validated', name='fix_validation_status'), nullable=False),
    sa.Column('validation_detail', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='fix_confidence'), nullable=True),
    sa.Column('patch', sa.Text(), nullable=True),
    sa.Column('breaking_risk', sa.Enum('none', 'low', 'high', name='fix_breaking_risk'), nullable=True),
    sa.Column('test_suggestion', sa.Text(), nullable=True),
    sa.Column('file_changes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('shared_with_finding_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('user_hint', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('llm_call_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_fix_suggestions_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], name=op.f('fk_fix_suggestions_llm_call_id_llm_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_fix_suggestions_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fix_suggestions')),
    sa.UniqueConstraint('finding_id', name=op.f('uq_fix_suggestions_finding_id'))
    )
    op.create_index(op.f('ix_fix_suggestions_scan_id'), 'fix_suggestions', ['scan_id'], unique=False)
    op.add_column('scans', sa.Column('analysis_partial', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('scans', sa.Column('enrichment_status', postgresql.ENUM(name='enrichment_status', create_type=False), nullable=True))
    op.add_column('scans', sa.Column('enrichment_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'enrichment_error')
    op.drop_column('scans', 'enrichment_status')
    op.drop_column('scans', 'analysis_partial')
    op.drop_index(op.f('ix_fix_suggestions_scan_id'), table_name='fix_suggestions')
    op.drop_table('fix_suggestions')
    op.drop_table('architecture_reviews')
    op.drop_index('ix_llm_calls_scan_id_purpose', table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###

    for enum_name in (
        'enrichment_status',
        'fix_status',
        'fix_validation_status',
        'fix_confidence',
        'fix_breaking_risk',
        'architecture_review_status',
        'llm_purpose',
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)

    # Postgres can't drop enum values: rebuild scan_status without the LLM stage states.
    op.execute(
        "UPDATE scans SET status = 'completed' WHERE status IN ('analysis_complete', 'enriching')"
    )
    op.execute("ALTER TYPE scan_status RENAME TO scan_status_old")
    op.execute(
        "CREATE TYPE scan_status AS ENUM ('queued', 'running', 'completed', 'partial', 'failed')"
    )
    op.execute("DROP INDEX IF EXISTS ix_scans_status")
    op.execute(
        "ALTER TABLE scans ALTER COLUMN status TYPE scan_status USING status::text::scan_status"
    )
    op.execute("CREATE INDEX ix_scans_status ON scans (status)")
    op.execute("DROP TYPE scan_status_old")
