"""site analyses

Revision ID: a182eb19a3c8
Revises: 40a5c99787b8
Create Date: 2026-09-17 00:17:44.045662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a182eb19a3c8'
down_revision: Union[str, Sequence[str], None] = '40a5c99787b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written: new enum value (autogenerate doesn't detect it).
    op.execute("ALTER TYPE llm_purpose ADD VALUE IF NOT EXISTS 'design_vision'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='site_analysis_status'), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('screenshot_key', sa.String(length=1024), nullable=True),
    sa.Column('full_screenshot_key', sa.String(length=1024), nullable=True),
    sa.Column('favicon_key', sa.String(length=1024), nullable=True),
    sa.Column('dom_key', sa.String(length=1024), nullable=True),
    sa.Column('capture', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('risk_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('design_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('design_notes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cached_from_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cached_from_id'], ['site_analyses.id'], name=op.f('fk_site_analyses_cached_from_id_site_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_site_analyses_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_analyses'))
    )
    op.create_index('ix_site_analyses_normalized_url_created_at', 'site_analyses', ['normalized_url', 'created_at'], unique=False)
    op.create_index('ix_site_analyses_user_id_created_at', 'site_analyses', ['user_id', 'created_at'], unique=False)
    op.add_column('llm_calls', sa.Column('site_analysis_id', sa.Uuid(), nullable=True))
    op.alter_column('llm_calls', 'scan_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_llm_calls_site_analysis_id', 'llm_calls', ['site_analysis_id'], unique=False)
    op.create_foreign_key(op.f('fk_llm_calls_site_analysis_id_site_analyses'), 'llm_calls', 'site_analyses', ['site_analysis_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f('ck_llm_calls_one_subject'), 'llm_calls', 'num_nonnulls(scan_id, site_analysis_id) = 1'
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_llm_calls_one_subject'), 'llm_calls', type_='check')
    # Calls billed to site analyses can't exist in the old schema.
    op.execute("DELETE FROM llm_calls WHERE scan_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_llm_calls_site_analysis_id_site_analyses'), 'llm_calls', type_='foreignkey')
    op.drop_index('ix_llm_calls_site_analysis_id', table_name='llm_calls')
    op.alter_column('llm_calls', 'scan_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('llm_calls', 'site_analysis_id')
    op.drop_index('ix_site_analyses_user_id_created_at', table_name='site_analyses')
    op.drop_index('ix_site_analyses_normalized_url_created_at', table_name='site_analyses')
    op.drop_table('site_analyses')
    # ### end Alembic commands ###
    sa.Enum(name='site_analysis_status').drop(op.get_bind(), checkfirst=True)
    # Postgres can't remove an enum value; 'design_vision' stays in llm_purpose, unused.
