"""github integration

Revision ID: 40a5c99787b8
Revises: d74cfd6c3bc1
Create Date: 2026-09-16 23:34:53.638851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a5c99787b8'
down_revision: Union[str, Sequence[str], None] = 'd74cfd6c3bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written: add_column doesn't create the enum type.
    postgresql.ENUM('upload', 'github', name='scan_source').create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('github_identities',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('github_user_id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_github_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_identities')),
    sa.UniqueConstraint('github_user_id', name=op.f('uq_github_identities_github_user_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_github_identities_user_id'))
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('previewed', 'creating', 'open', 'failed', name='pull_request_status'), nullable=False),
    sa.Column('repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('head_repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('base_branch', sa.String(length=255), nullable=False),
    sa.Column('base_sha', sa.String(length=40), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('use_fork', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('included_suggestion_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preview_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('combined_diff', sa.Text(), nullable=False),
    sa.Column('commits', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(length=1024), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_pull_requests_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pull_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pull_requests'))
    )
    op.create_index(op.f('ix_pull_requests_scan_id'), 'pull_requests', ['scan_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_user_id'), 'pull_requests', ['user_id'], unique=False)
    op.add_column('scans', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('scans', sa.Column('source', sa.Enum('upload', 'github', name='scan_source'), server_default='upload', nullable=False))
    op.add_column('scans', sa.Column('repo_owner', sa.String(length=100), nullable=True))
    op.add_column('scans', sa.Column('repo_name', sa.String(length=100), nullable=True))
    op.add_column('scans', sa.Column('repo_ref', sa.String(length=255), nullable=True))
    op.add_column('scans', sa.Column('repo_default_branch', sa.String(length=255), nullable=True))
    op.add_column('scans', sa.Column('commit_sha', sa.String(length=40), nullable=True))
    op.add_column('scans', sa.Column('repo_private', sa.Boolean(), nullable=True))
    op.alter_column('scans', 'storage_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.create_index('ix_scans_repo', 'scans', ['repo_owner', 'repo_name', 'commit_sha'], unique=False)
    op.create_index('ix_scans_user_id_created_at', 'scans', ['user_id', 'created_at'], unique=False)
    op.create_foreign_key(op.f('fk_scans_user_id_users'), 'scans', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_scans_user_id_users'), 'scans', type_='foreignkey')
    op.drop_index('ix_scans_user_id_created_at', table_name='scans')
    op.drop_index('ix_scans_repo', table_name='scans')
    # Repository scans have no stored archive and can't exist in the old schema.
    op.execute("DELETE FROM scans WHERE storage_key IS NULL")
    op.alter_column('scans', 'storage_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('scans', 'repo_private')
    op.drop_column('scans', 'commit_sha')
    op.drop_column('scans', 'repo_default_branch')
    op.drop_column('scans', 'repo_ref')
    op.drop_column('scans', 'repo_name')
    op.drop_column('scans', 'repo_owner')
    op.drop_column('scans', 'source')
    op.drop_column('scans', 'user_id')
    op.drop_index(op.f('ix_pull_requests_user_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_scan_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('github_identities')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
    for enum_name in ('pull_request_status', 'scan_source'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
