"""create scans and findings

Revision ID: 9cf8b4365b12
Revises: 
Create Date: 2026-09-13 23:09:53.525337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cf8b4365b12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='scan_status'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('detected_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('analyzer', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', 'critical', name='finding_severity'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_findings_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index('ix_findings_scan_id_file_path', 'findings', ['scan_id', 'file_path'], unique=False)
    op.create_index('ix_findings_scan_id_severity', 'findings', ['scan_id', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_scan_id_severity', table_name='findings')
    op.drop_index('ix_findings_scan_id_file_path', table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_table('scans')
    # Postgres enum types outlive drop_table; remove them explicitly.
    sa.Enum(name='finding_severity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='scan_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
