"""analyzer runs, finding corroboration, partial scans

Revision ID: 257851ff0102
Revises: 9cf8b4365b12
Create Date: 2026-09-16 18:50:20.897297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '257851ff0102'
down_revision: Union[str, Sequence[str], None] = '9cf8b4365b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written: autogenerate does not detect new enum values. ADD VALUE is
    # allowed inside a transaction (PG >= 12) as long as the value isn't used in it.
    op.execute("ALTER TYPE scan_status ADD VALUE IF NOT EXISTS 'partial' AFTER 'completed'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzer_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('analyzer_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'timed_out', 'skipped', name='analyzer_run_status'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('finding_count', sa.Integer(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_analyzer_runs_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyzer_runs')),
    sa.UniqueConstraint('scan_id', 'analyzer_name', name=op.f('uq_analyzer_runs_scan_id'))
    )
    op.add_column('findings', sa.Column('category', sa.String(length=512), nullable=True))
    op.add_column('findings', sa.Column('corroborated_by', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False))
    op.add_column('findings', sa.Column('merged_from', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('findings', sa.Column('dependency', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_findings_scan_id_analyzer', 'findings', ['scan_id', 'analyzer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_scan_id_analyzer', table_name='findings')
    op.drop_column('findings', 'dependency')
    op.drop_column('findings', 'merged_from')
    op.drop_column('findings', 'corroborated_by')
    op.drop_column('findings', 'category')
    op.drop_table('analyzer_runs')
    # Postgres enum types outlive drop_table; remove them explicitly.
    sa.Enum(name='analyzer_run_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

    # Postgres can't drop an enum value: rebuild scan_status without 'partial'.
    op.execute("UPDATE scans SET status = 'completed' WHERE status = 'partial'")
    op.execute("ALTER TYPE scan_status RENAME TO scan_status_old")
    op.execute("CREATE TYPE scan_status AS ENUM ('queued', 'running', 'completed', 'failed')")
    op.execute("DROP INDEX IF EXISTS ix_scans_status")
    op.execute(
        "ALTER TABLE scans ALTER COLUMN status TYPE scan_status "
        "USING status::text::scan_status"
    )
    op.execute("CREATE INDEX ix_scans_status ON scans (status)")
    op.execute("DROP TYPE scan_status_old")
