"""architecture graph

Revision ID: 32553c8021fb
Revises: 257851ff0102
Create Date: 2026-09-16 21:18:58.747220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32553c8021fb'
down_revision: Union[str, Sequence[str], None] = '257851ff0102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_issues',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('issue_type', sa.Enum('circular_dependency', 'layer_violation', 'god_module', 'orphan_module', name='architecture_issue_type'), nullable=False),
    # finding_severity already exists (findings table): reuse it, don't create it.
    sa.Column('severity', postgresql.ENUM('info', 'warning', 'error', 'critical', name='finding_severity', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('involved_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('involved_edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_architecture_issues_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_architecture_issues'))
    )
    op.create_index('ix_architecture_issues_scan_id_issue_type', 'architecture_issues', ['scan_id', 'issue_type'], unique=False)
    op.create_table('architecture_summaries',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_architecture_summaries_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id', name=op.f('pk_architecture_summaries'))
    )
    op.create_table('graph_edges',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('source_module', sa.Text(), nullable=False),
    sa.Column('target_module', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('internal', 'external', 'unresolved', name='graph_edge_kind'), nullable=False),
    sa.Column('import_statement', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('import_count', sa.Integer(), nullable=False),
    sa.Column('type_only', sa.Boolean(), nullable=False),
    sa.Column('lazy', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_graph_edges_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges'))
    )
    op.create_index('ix_graph_edges_scan_id_source_module', 'graph_edges', ['scan_id', 'source_module'], unique=False)
    op.create_index('ix_graph_edges_scan_id_target_module', 'graph_edges', ['scan_id', 'target_module'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('loc', sa.Integer(), nullable=False),
    sa.Column('definition_count', sa.Integer(), nullable=False),
    sa.Column('fan_in', sa.Integer(), nullable=False),
    sa.Column('fan_out', sa.Integer(), nullable=False),
    sa.Column('instability', sa.Float(), nullable=True),
    sa.Column('centrality', sa.Float(), nullable=False),
    sa.Column('inferred_layer', sa.String(length=32), nullable=True),
    sa.Column('layer_stack', sa.String(length=32), nullable=True),
    sa.Column('is_entrypoint', sa.Boolean(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_graph_nodes_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_nodes')),
    sa.UniqueConstraint('scan_id', 'module_id', name=op.f('uq_graph_nodes_scan_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_nodes')
    op.drop_index('ix_graph_edges_scan_id_target_module', table_name='graph_edges')
    op.drop_index('ix_graph_edges_scan_id_source_module', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_table('architecture_summaries')
    op.drop_index('ix_architecture_issues_scan_id_issue_type', table_name='architecture_issues')
    op.drop_table('architecture_issues')
    # Postgres enum types outlive drop_table; remove the ones this revision created.
    sa.Enum(name='graph_edge_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='architecture_issue_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
