"""Fix pull requests: build a preview, and only on explicit confirmation write to GitHub.

Guarantees:
- Only suggestions whose patch was validated (`validation_status == valid`) are used.
- Patches are re-applied to the *current* head of the base branch. If the branch
  moved since the scan, each patch is re-checked there; patches that no longer
  apply (or that conflict with another selected fix) are reported and left out,
  never forced.
- One commit per logical fix group, on a new branch `codeaudit/fix-<scan>`.
- `create_pull_request_from_preview` is the only function here that writes to
  GitHub, and it refuses to run unless the plan still matches the fingerprint of
  the preview the user confirmed. Nothing in scanning or enrichment calls it.
"""

import dataclasses
import difflib
import hashlib
import json
import logging
import tempfile
import time
from collections import Counter, OrderedDict
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.config import get_settings
from app.models import (
    Finding,
    FixStatus,
    FixSuggestion,
    GitHubIdentity,
    PullRequest,
    PullRequestStatus,
    Scan,
    ScanSource,
    Severity,
    User,
    ValidationStatus,
)
from app.services.auth.oauth import access_token
from app.services.github.client import (
    GitHubAuthError,
    GitHubClient,
    GitHubError,
    GitHubNotFoundError,
    GitHubPermissionError,
    GitHubValidationError,
)
from app.services.github.urls import SHA
from app.services.llm.patches import apply_patch_in_place, patch_paths, syntax_error
from app.services.scoring.service import project

logger = logging.getLogger(__name__)

MAX_BRANCH_SUFFIX = 20
AI_NOTICE = (
    "> [!WARNING]\n"
    "> These changes were generated by an AI model and validated only to the extent that each"
    " patch applies cleanly and the changed files still parse. They have **not** been compiled,"
    " type-checked or tested. A human must review every change before merging."
)


class PullRequestError(Exception):
    """User-facing failure with a stable, distinct code."""

    def __init__(
        self,
        code: str,
        message: str,
        *,
        http_status: int = 409,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.http_status = http_status
        self.details = details or {}


@dataclass
class FixGroup:
    """Suggestions that share one generated patch (a grouped LLM request)."""

    suggestions: list[FixSuggestion]
    findings: list[Finding]
    patch: str

    @property
    def suggestion_ids(self) -> list[int]:
        return sorted(s.id for s in self.suggestions)

    @property
    def paths(self) -> list[str]:
        return patch_paths(self.patch)


@dataclass
class PatchCheck:
    suggestion_ids: list[int]
    paths: list[str]
    status: str  # applies | no_longer_applies | conflicts | syntax_error
    detail: str | None = None


@dataclass
class PullRequestPlan:
    repo_full_name: str
    head_repo_full_name: str
    base_branch: str
    base_sha: str
    scanned_sha: str
    head_moved: bool
    can_push: bool
    requires_fork: bool
    use_fork: bool
    branch: str
    branch_available: bool
    suggested_branch: str | None
    groups: list[FixGroup]
    excluded: list[dict[str, Any]]
    patch_checks: list[PatchCheck]
    files: dict[str, tuple[str, str]]  # path -> (original at base, final)
    combined_diff: str
    score: dict[str, Any]
    title: str
    body: str
    fingerprint: str
    blocking: list[dict[str, str]] = field(default_factory=list)

    @property
    def included_suggestion_ids(self) -> list[int]:
        return sorted(i for g in self.groups for i in g.suggestion_ids)


# ----------------------------------------------------------------------------- helpers


def default_branch_name(scan: Scan) -> str:
    return f"codeaudit/fix-{scan.id.hex[:8]}"


def _token(db: Session, user: User) -> tuple[str, GitHubIdentity]:
    identity = db.scalar(select(GitHubIdentity).where(GitHubIdentity.user_id == user.id))
    if identity is None or identity.access_token_encrypted is None:
        raise PullRequestError(
            "github_auth_required", "Connect GitHub to open pull requests.", http_status=401
        )
    try:
        return access_token(db, identity), identity
    except GitHubAuthError as exc:
        raise PullRequestError("github_auth_required", exc.message, http_status=401) from None


def _map_github_error(exc: GitHubError, *, stage: str) -> PullRequestError:
    message = (exc.details.get("github_message") or exc.message or "").lower()
    errors = " ".join(exc.details.get("github_errors", [])).lower()
    text = f"{message} {errors}"
    if isinstance(exc, GitHubAuthError):
        return PullRequestError("github_auth_required", exc.message, http_status=401)
    if (
        "protected branch" in text
        or "branch protection" in text
        or ("protected" in text and stage == "branch")
        or ("rule violation" in text and stage == "branch")
    ):
        return PullRequestError(
            "branch_protected",
            "A branch protection rule blocks creating this branch. Choose a branch name that isn't"
            " covered by the repository's protection rules, or ask a maintainer to allow it.",
        )
    if stage == "branch" and (
        "reference already exists" in text
        or isinstance(exc, GitHubValidationError)
        and "already exists" in text
    ):
        return PullRequestError(
            "branch_exists",
            "A branch with this name already exists. Preview again to get a free branch name.",
        )
    if stage == "pull_request" and "already exists" in text:
        return PullRequestError(
            "pull_request_exists", "A pull request for this branch already exists on GitHub."
        )
    if isinstance(exc, GitHubPermissionError) or (
        isinstance(exc, GitHubNotFoundError) and stage != "read"
    ):
        return PullRequestError(
            "insufficient_permissions",
            "Your GitHub account can't write to this repository. Open the pull request from a fork"
            " instead, or reconnect GitHub with private repository access if it's private.",
            http_status=403,
        )
    return PullRequestError(exc.code, exc.message, http_status=exc.http_status)


def load_groups(
    db: Session, scan: Scan, suggestion_ids: Sequence[int]
) -> tuple[list[FixGroup], list[dict[str, Any]]]:
    """Valid suggestions grouped by shared patch; everything else goes to `excluded`."""
    requested = list(dict.fromkeys(suggestion_ids))
    rows = {
        s.id: s
        for s in db.scalars(select(FixSuggestion).where(FixSuggestion.id.in_(requested))).all()
    }
    excluded: list[dict[str, Any]] = []
    grouped: OrderedDict[tuple[int | None, str], list[FixSuggestion]] = OrderedDict()
    for suggestion_id in requested:
        suggestion = rows.get(suggestion_id)
        if suggestion is None or suggestion.scan_id != scan.id:
            excluded.append(
                {"suggestion_id": suggestion_id, "reason": "not a suggestion of this scan"}
            )
        elif (
            suggestion.status is not FixStatus.READY
            or suggestion.validation_status is not ValidationStatus.VALID
            or not suggestion.patch
        ):
            excluded.append(
                {
                    "suggestion_id": suggestion_id,
                    "reason": (
                        f"patch not verified ({suggestion.validation_status.value});"
                        " only verified patches can be included"
                    ),
                }
            )
        else:
            grouped.setdefault((suggestion.llm_call_id, suggestion.patch), []).append(suggestion)
    finding_ids = {s.finding_id for group in grouped.values() for s in group}
    findings = {
        f.id: f for f in db.scalars(select(Finding).where(Finding.id.in_(finding_ids))).all()
    }
    groups = [
        FixGroup(
            members, [findings[s.finding_id] for s in members if s.finding_id in findings], patch
        )
        for (_, patch), members in grouped.items()
    ]
    return groups, excluded


def _unified(path: str, before: str, after: str) -> str:
    return "".join(
        difflib.unified_diff(
            before.splitlines(keepends=True),
            after.splitlines(keepends=True),
            f"a/{path}",
            f"b/{path}",
        )
    )


def _category(group: FixGroup) -> str:
    analyzers = {f.analyzer for f in group.findings}
    if analyzers == {"dependency"}:
        return "deps"
    if analyzers <= {"ruff"}:
        return "lint"
    return "security"


def commit_message(group: FixGroup, scan: Scan) -> str:
    severity_order = list(Severity)
    worst = (
        max(group.findings, key=lambda f: severity_order.index(f.severity))
        if group.findings
        else None
    )
    subject_detail = (
        worst.dependency.get("package")
        if worst and worst.dependency
        else (worst.rule_id.rsplit(".", 1)[-1] if worst else "issue")
    )
    paths = group.paths
    where = paths[0] if len(paths) == 1 else f"{len(paths)} files"
    subject = f"fix({_category(group)}): address {subject_detail} in {where}"[:72]
    explanation = (group.suggestions[0].explanation or "").strip()
    lines = [subject, "", *_wrap(explanation, 72), ""]
    lines += [
        f"- {f.severity.value}: {f.rule_id} ({f.file_path}:{f.start_line})" for f in group.findings
    ]
    lines += ["", "AI-generated by CodeAudit; review before merging.", f"CodeAudit-Scan: {scan.id}"]
    return "\n".join(lines)


def _s(count: int) -> str:
    return "" if count == 1 else "s"


def _wrap(text: str, width: int) -> list[str]:
    import textwrap

    return textwrap.wrap(text, width) if text else []


def render_body(
    plan_groups: list[FixGroup],
    scan: Scan,
    score: dict[str, Any],
    excluded: list[dict[str, Any]],
    checks: list[PatchCheck],
    head_moved: bool,
) -> str:
    findings = [f for g in plan_groups for f in g.findings]
    counts = Counter(f.severity.value for f in findings)
    lines = [
        "## CodeAudit fixes",
        "",
        AI_NOTICE,
        "",
        f"This pull request addresses **{len(findings)} finding{_s(len(findings))}** in"
        f" {len(plan_groups)} commit{_s(len(plan_groups))}, from the CodeAudit scan of"
        f" `{scan.commit_sha[:12] if scan.commit_sha else 'unknown'}`.",
        "",
        "### Severity breakdown",
        "",
        "| Severity | Findings fixed |",
        "|---|---|",
        *[
            f"| {severity.value} | {counts[severity.value]} |"
            for severity in reversed(list(Severity))
            if counts[severity.value]
        ],
        "",
        "### Score projection",
        "",
    ]
    if score.get("current") is None:
        lines.append("No score is available for this scan.")
    else:
        lines.append(
            f"**{score['current']:.1f}** ({score['current_grade']}) → **{score['projected']:.1f}**"
            f" ({score['projected_grade']}), {score['delta']:+.2f} points if these fixes are merged"
            f" (CodeAudit rubric v{score['rubric_version']}"
            f"{', incomplete scan' if score.get('incomplete') else ''})."
        )
    lines += ["", "### Fixes", ""]
    for index, group in enumerate(plan_groups, start=1):
        suggestion = group.suggestions[0]
        lines.append(f"#### {index}. {', '.join(sorted({f.rule_id for f in group.findings}))}")
        lines.append("")
        for finding in group.findings:
            lines.append(
                f"- **{finding.severity.value}** `{finding.file_path}:{finding.start_line}`:"
                f" {finding.message[:200]}"
            )
        lines.append("")
        if suggestion.explanation:
            lines += [suggestion.explanation.strip(), ""]
        lines.append(
            f"Confidence: {suggestion.confidence.value if suggestion.confidence else 'n/a'} ·"
            " Breaking risk:"
            f" {suggestion.breaking_risk.value if suggestion.breaking_risk else 'n/a'}"
        )
        if suggestion.test_suggestion:
            lines += ["", f"Suggested regression test: {suggestion.test_suggestion.strip()}"]
        lines.append("")
    not_applied = [c for c in checks if c.status != "applies"]
    if excluded or not_applied:
        lines += ["### Not included", ""]
        for check in not_applied:
            lines.append(
                f"- Suggestions {check.suggestion_ids} ({', '.join(check.paths)}):"
                f" {check.status.replace('_', ' ')}"
            )
        for item in excluded:
            lines.append(f"- Suggestion {item['suggestion_id']}: {item['reason']}")
        lines.append("")
    if head_moved:
        lines += [
            "The base branch has moved since the scanned commit; every included patch was"
            " re-checked"
            " against its current head.",
            "",
        ]
    lines.append(
        "<sub>Opened with CodeAudit after explicit confirmation by the repository user.</sub>"
    )
    return "\n".join(lines)


def _fingerprint(
    base_sha: str, head_repo: str, branch: str, use_fork: bool, groups: list[FixGroup]
) -> str:
    material = json.dumps(
        {
            "base_sha": base_sha,
            "head_repo": head_repo,
            "branch": branch,
            "use_fork": use_fork,
            "groups": [
                [g.suggestion_ids, hashlib.sha256(g.patch.encode()).hexdigest()] for g in groups
            ],
        },
        sort_keys=True,
    )
    return hashlib.sha256(material.encode()).hexdigest()


# ----------------------------------------------------------------------------- plan


def build_plan(
    db: Session,
    scan: Scan,
    user: User,
    suggestion_ids: Sequence[int],
    *,
    branch: str | None = None,
    use_fork: bool = False,
    github: GitHubClient | None = None,
) -> PullRequestPlan:
    """Everything the PR would contain, computed against GitHub's current state. Read-only."""
    if scan.source is not ScanSource.GITHUB or not (
        scan.repo_owner and scan.repo_name and scan.commit_sha
    ):
        raise PullRequestError(
            "not_a_repository_scan",
            "Pull requests can only be opened for scans of a GitHub repository.",
            http_status=400,
        )
    groups, excluded = load_groups(db, scan, suggestion_ids)
    if not groups:
        raise PullRequestError(
            "no_valid_suggestions",
            "None of the selected suggestions has a verified patch.",
            http_status=422,
            details={"excluded": excluded},
        )

    token, identity = _token(db, user)
    client = github or GitHubClient(token)
    owner, name = scan.repo_owner, scan.repo_name
    try:
        repo = client.get_repo(owner, name)
        base_branch = (
            scan.repo_ref if scan.repo_ref and not SHA.match(scan.repo_ref) else repo.default_branch
        )
        try:
            base_sha = client.get_branch_head(owner, name, base_branch)
        except GitHubNotFoundError:  # the scan was of a tag or the branch is gone
            base_branch = repo.default_branch
            base_sha = client.get_branch_head(owner, name, base_branch)
        head_moved = base_sha != scan.commit_sha

        # Reproduce every change on the current base, fix group by fix group.
        originals: dict[str, str | None] = {}
        for group in groups:
            for path in group.paths:
                if path not in originals:
                    originals[path] = client.get_file(owner, name, path, base_sha)
    except GitHubError as exc:
        raise _map_github_error(exc, stage="read") from None
    finally:
        if github is None:
            client.close()

    checks: list[PatchCheck] = []
    applied_groups: list[FixGroup] = []
    with tempfile.TemporaryDirectory(prefix="codeaudit-pr-") as tmp:
        work = Path(tmp)
        for path, content in originals.items():
            if content is not None:
                (work / path).parent.mkdir(parents=True, exist_ok=True)
                (work / path).write_text(content, encoding="utf-8", errors="surrogateescape")
        for group in groups:
            missing = [p for p in group.paths if originals.get(p) is None]
            if missing:
                checks.append(
                    PatchCheck(
                        group.suggestion_ids,
                        group.paths,
                        "no_longer_applies",
                        f"{', '.join(missing)} no longer exists on {base_branch}",
                    )
                )
                continue
            snapshot = {
                p: (work / p).read_text(encoding="utf-8", errors="surrogateescape")
                for p in group.paths
            }
            ok, error = apply_patch_in_place(work, group.patch)
            if not ok:
                # Validated against the scanned commit: failing now means the base moved or
                # an earlier selected fix changed the same lines.
                touched_by_earlier = any(set(group.paths) & set(g.paths) for g in applied_groups)
                status = (
                    "conflicts" if touched_by_earlier and not head_moved else "no_longer_applies"
                )
                checks.append(PatchCheck(group.suggestion_ids, group.paths, status, error))
                continue
            broken = next(
                (
                    err
                    for p in group.paths
                    if (
                        err := syntax_error(
                            p, (work / p).read_text(encoding="utf-8", errors="surrogateescape")
                        )
                    )
                ),
                None,
            )
            if broken:
                for path, content in snapshot.items():
                    (work / path).write_text(content, encoding="utf-8", errors="surrogateescape")
                checks.append(PatchCheck(group.suggestion_ids, group.paths, "syntax_error", broken))
                continue
            checks.append(PatchCheck(group.suggestion_ids, group.paths, "applies"))
            applied_groups.append(group)
        files = {
            path: (
                originals[path] or "",
                (work / path).read_text(encoding="utf-8", errors="surrogateescape"),
            )
            for path in originals
            if originals[path] is not None and any(path in g.paths for g in applied_groups)
        }

    blocking: list[dict[str, str]] = []
    if not applied_groups:
        blocking.append(
            {
                "code": "stale_head" if head_moved else "merge_conflict",
                "message": "None of the selected patches applies to the current base branch.",
            }
        )

    requires_fork = not bool(repo.can_push)
    head_repo = f"{identity.login}/{name}" if use_fork else f"{owner}/{name}"
    if requires_fork and not use_fork:
        blocking.append(
            {
                "code": "fork_required",
                "message": (
                    f"Your GitHub account ({identity.login}) can't push to {owner}/{name}."
                    " Confirm opening the pull request from a fork."
                ),
            }
        )

    wanted = branch or default_branch_name(scan)
    branch_available, suggested = True, None
    with GitHubClient(token) if github is None else _nullcontext(github) as reader:
        try:
            head_owner, head_name = head_repo.split("/")
            if reader.branch_exists(head_owner, head_name, wanted):
                branch_available = False
                for suffix in range(2, MAX_BRANCH_SUFFIX + 2):
                    candidate = f"{wanted}-{suffix}"
                    if not reader.branch_exists(head_owner, head_name, candidate):
                        suggested = candidate
                        break
        except GitHubNotFoundError:
            pass  # the fork doesn't exist yet: every name is free
        except GitHubError as exc:
            raise _map_github_error(exc, stage="read") from None
    if not branch_available:
        blocking.append(
            {
                "code": "branch_exists",
                "message": f"Branch {wanted} already exists in {head_repo}."
                + (f" Use {suggested}." if suggested else ""),
            }
        )

    finding_ids = [f.id for g in applied_groups for f in g.findings]
    projection = project(db, scan, finding_ids)
    score = {
        "current": projection.current.overall,
        "current_grade": projection.current.grade,
        "projected": projection.projected.overall,
        "projected_grade": projection.projected.grade,
        "delta": projection.delta,
        "rubric_version": projection.current.rubric_version,
        "incomplete": projection.current.incomplete,
    }
    count = len(finding_ids)
    kinds = sorted({_category(g) for g in applied_groups})
    title = (
        f"CodeAudit: fix {count} finding{'s' if count != 1 else ''} ({', '.join(kinds)})"
        if applied_groups
        else "CodeAudit fixes"
    )
    return PullRequestPlan(
        repo_full_name=f"{owner}/{name}",
        head_repo_full_name=head_repo,
        base_branch=base_branch,
        base_sha=base_sha,
        scanned_sha=scan.commit_sha,
        head_moved=head_moved,
        can_push=not requires_fork,
        requires_fork=requires_fork,
        use_fork=use_fork,
        branch=wanted,
        branch_available=branch_available,
        suggested_branch=suggested,
        groups=applied_groups,
        excluded=excluded,
        patch_checks=checks,
        files=files,
        combined_diff="".join(
            _unified(p, before, after) for p, (before, after) in sorted(files.items())
        ),
        score=score,
        title=title,
        body=render_body(applied_groups, scan, score, excluded, checks, head_moved),
        fingerprint=_fingerprint(base_sha, head_repo, wanted, use_fork, applied_groups),
        blocking=blocking,
    )


class _nullcontext:
    def __init__(self, value: GitHubClient) -> None:
        self.value = value

    def __enter__(self) -> GitHubClient:
        return self.value

    def __exit__(self, *_: object) -> None:
        return None


def save_preview(db: Session, scan: Scan, user: User, plan: PullRequestPlan) -> PullRequest:
    row = PullRequest(
        scan_id=scan.id,
        user_id=user.id,
        status=PullRequestStatus.PREVIEWED,
        repo_full_name=plan.repo_full_name,
        head_repo_full_name=plan.head_repo_full_name,
        base_branch=plan.base_branch,
        base_sha=plan.base_sha,
        branch=plan.branch,
        use_fork=plan.use_fork,
        title=plan.title,
        body=plan.body,
        included_suggestion_ids=plan.included_suggestion_ids,
        preview_fingerprint=plan.fingerprint,
        combined_diff=plan.combined_diff,
    )
    db.add(row)
    db.commit()
    return row


# ----------------------------------------------------------------------------- writes


def _ensure_fork(
    github: GitHubClient, owner: str, name: str, login: str, base_branch: str, default_branch: str
) -> None:
    try:
        existing = github.get_repo(login, name)
        if existing.fork:
            return
        raise PullRequestError(
            "fork_name_taken",
            f"You already have a repository named {login}/{name} that isn't a fork of"
            f" {owner}/{name}.",
        )
    except GitHubNotFoundError:
        pass
    github.create_fork(owner, name, default_branch_only=base_branch == default_branch)
    deadline = time.monotonic() + get_settings().github_fork_wait_seconds
    while True:  # forks are created asynchronously
        try:
            github.get_branch_head(login, name, base_branch)
            return
        except GitHubNotFoundError:
            if time.monotonic() > deadline:
                raise PullRequestError(
                    "fork_not_ready", "GitHub is still creating your fork. Try again in a minute."
                ) from None
            time.sleep(2)


def create_pull_request_from_preview(
    db: Session,
    preview: PullRequest,
    scan: Scan,
    user: User,
    *,
    github: GitHubClient | None = None,
) -> PullRequest:
    """Create the branch, commits and pull request for a confirmed preview.

    The plan is rebuilt first; if it no longer matches what the user previewed
    (base moved, patches changed, branch taken), nothing is written.
    """
    if preview.status is not PullRequestStatus.CREATING or preview.confirmed_at is None:
        raise PullRequestError("not_confirmed", "This pull request has not been confirmed.")
    token, identity = _token(db, user)
    client = github or GitHubClient(token)
    try:
        plan = build_plan(
            db,
            scan,
            user,
            preview.included_suggestion_ids,
            branch=preview.branch,
            use_fork=preview.use_fork,
            github=client,
        )
        if plan.fingerprint != preview.preview_fingerprint:
            raise PullRequestError(
                "preview_outdated",
                "The repository or the selected fixes changed after the preview (for example new"
                " commits on the base branch). Open a new preview and confirm again.",
                details={"head_moved": plan.head_moved, "blocking": plan.blocking},
            )
        blocking = [
            b for b in plan.blocking if not (b["code"] == "fork_required" and plan.use_fork)
        ]
        if blocking:
            raise PullRequestError(
                blocking[0]["code"], blocking[0]["message"], details={"blocking": blocking}
            )

        owner, name = plan.repo_full_name.split("/")
        head_owner, head_name = plan.head_repo_full_name.split("/")
        stage = "fork"
        try:
            if plan.use_fork:
                repo = client.get_repo(owner, name)
                _ensure_fork(
                    client, owner, name, identity.login, plan.base_branch, repo.default_branch
                )

            stage = "commits"
            parent = plan.base_sha
            try:
                tree = client.get_commit_tree(head_owner, head_name, parent)
            except (GitHubNotFoundError, GitHubValidationError):
                if not plan.use_fork:
                    raise
                # An older fork may not have the base commit yet.
                client.sync_fork(head_owner, head_name, plan.base_branch)
                tree = client.get_commit_tree(head_owner, head_name, parent)
            commits: list[dict[str, Any]] = []
            # Replay each group's change on top of the previous commit.
            with tempfile.TemporaryDirectory(prefix="codeaudit-pr-") as tmp:
                work = Path(tmp)
                for path, (before, _) in plan.files.items():
                    (work / path).parent.mkdir(parents=True, exist_ok=True)
                    (work / path).write_text(before, encoding="utf-8", errors="surrogateescape")
                for group in plan.groups:
                    ok, error = apply_patch_in_place(work, group.patch)
                    if not ok:  # can't happen if the plan matched; never force
                        raise PullRequestError(
                            "merge_conflict", f"A patch stopped applying: {error}"
                        )
                    entries = {
                        path: (
                            client.create_blob(
                                head_owner,
                                head_name,
                                (work / path).read_text(encoding="utf-8", errors="surrogateescape"),
                            ),
                            client.get_file_mode(head_owner, head_name, plan.base_sha, path),
                        )
                        for path in group.paths
                    }
                    tree = client.create_tree(head_owner, head_name, tree, entries)
                    parent = client.create_commit(
                        head_owner, head_name, commit_message(group, scan), tree, parent
                    )
                    commits.append(
                        {
                            "sha": parent,
                            "message": commit_message(group, scan).split("\n", 1)[0],
                            "suggestion_ids": group.suggestion_ids,
                        }
                    )

            stage = "branch"
            client.create_branch(head_owner, head_name, plan.branch, parent)
            stage = "pull_request"
            head_ref = plan.branch if head_owner == owner else f"{head_owner}:{plan.branch}"
            created = client.create_pull_request(
                owner,
                name,
                title=preview.title,
                body=with_ai_notice(preview.body),
                head=head_ref,
                base=plan.base_branch,
            )
        except GitHubError as exc:
            raise _map_github_error(exc, stage=stage) from None
    finally:
        if github is None:
            client.close()

    preview.status = PullRequestStatus.OPEN
    preview.commits = commits
    preview.pr_number = int(created["number"])
    preview.pr_url = str(created["html_url"])
    preview.error_code = preview.error_message = None
    db.commit()
    logger.info("scan %s: opened %s with %d commits", scan.id, preview.pr_url, len(commits))
    return preview


def preview_details(plan: PullRequestPlan, scan: Scan) -> dict[str, Any]:
    """Plan fields shown in the preview, beyond what the PullRequest row stores."""
    return {
        "scanned_sha": plan.scanned_sha,
        "head_moved": plan.head_moved,
        "can_push": plan.can_push,
        "requires_fork": plan.requires_fork,
        "branch_available": plan.branch_available,
        "suggested_branch": plan.suggested_branch,
        "files": [
            {"path": path, "original": before, "patched": after}
            for path, (before, after) in sorted(plan.files.items())
        ],
        "planned_commits": [
            {
                "message": commit_message(group, scan),
                "suggestion_ids": group.suggestion_ids,
                "paths": group.paths,
            }
            for group in plan.groups
        ],
        "patch_checks": [dataclasses.asdict(check) for check in plan.patch_checks],
        "excluded": plan.excluded,
        "blocking": plan.blocking,
        "score": plan.score,
        "writes_to": plan.head_repo_full_name,
    }


def with_ai_notice(body: str) -> str:
    """The AI-generated warning can't be edited out of the pull request body."""
    return body if AI_NOTICE in body else f"{AI_NOTICE}\n\n{body}"
